---
- name: Set full path to secret file
  ansible.builtin.set_fact:
    full_secret_path: "{{ base_secret_path }}/{{ vault_def.vault_path }}"

- name: Fetch vault file to controller
  ansible.builtin.fetch:
    src: "{{ full_secret_path }}"
    dest: "/tmp/fetched_vault_{{ vault_def.vault_path | basename }}.yaml"
    flat: yes

- name: Include secret vars from fetched vault
  ansible.builtin.include_vars:
    file: "/tmp/fetched_vault_{{ vault_def.vault_path | basename }}.yaml"
    name: secrets_in_file

- name: Prepare content for output file
  ansible.builtin.set_fact:
    vault_file_content: |
      {% for item in secrets_in_file | dict2items %}
      {{ item.key }}: {{ item.value }}
      {% endfor %}

- name: Write secrets to file in /tmp
  ansible.builtin.copy:
    content: "{{ vault_file_content }}"
    dest: "/tmp/{{ vault_def.azure_vault }}-{{ vault_def.Environment }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  no_log: true
