---
- name: Listar todas as keys do Azure Key Vault
  azure.azcollection.azure_rm_keyvaultkey_info:
    keyvault_uri: "https://{{ azure_vault_name }}.vault.azure.net/"
  register: akv_keys_info
  delegate_to: localhost

- name: Remover todas as keys do Azure Key Vault
  when: akv_keys_info.keys is defined and akv_keys_info.keys | length > 0
  azure.azcollection.azure_rm_keyvaultkey:
    name: "{{ item.attributes.name }}"
    keyvault_uri: "https://{{ azure_vault_name }}.vault.azure.net/"
    state: absent
    # purge: true  # descomente se quiser purgar versões excluídas (soft-delete)
  loop: "{{ akv_keys_info.keys }}"
  loop_control:
    label: "{{ item.attributes.name }}"
  delegate_to: localhost

