---
# process_vault_file.yml

- name: Filter vault definitions for current vault_path
  ansible.builtin.set_fact:
    vault_definitions: "{{ defs.servicekeys | selectattr('vault_path', 'equalto', vault_path) | list }}"

- name: Set full path to secret file
  ansible.builtin.set_fact:
    full_secret_path: "{{ base_secret_path }}/{{ vault_path }}"

- name: Fetch vault file to controller
  ansible.builtin.fetch:
    src: "{{ full_secret_path }}"
    dest: "/tmp/fetched_{{ vault_path | basename }}"
    flat: yes

- name: Fix double colons in vault file
  ansible.builtin.shell: "sed -i 's/:$//' {{ full_secret_path }}"

- name: Include secret vars from fetched vault
  ansible.builtin.include_vars:
    file: "/tmp/fetched_{{ vault_path | basename }}"
    name: secrets_in_file

- name: Debug generated content
  ansible.builtin.debug:
    var: secrets_in_file

