- name: Filter vault definitions for current vault_path
  ansible.builtin.set_fact:
    vault_definitions: "{{ defs.servicekeys | selectattr('vault_path', 'equalto', vault_path) | list }}"

- name: Set full path to secret file
  ansible.builtin.set_fact:
    full_secret_path: "{{ base_secret_path }}/{{ vault_path }}"

- name: Fetch vault file to controller
  ansible.builtin.fetch:
    src: "{{ full_secret_path }}"
    dest: "/tmp/fetched_{{ vault_path | basename }}"
    flat: yes

- name: Include secret vars from fetched vault
  ansible.builtin.include_vars:
    file: "/tmp/fetched_{{ vault_path | basename }}"
    name: secrets_in_file
  no_log: false

- name: Upload each secret to Azure Key Vault (memory-efficient)
  azure.azcollection.azure_rm_keyvaultsecret:
    secret_name: "{{ entry.akv_secret_key }}"
    secret_value: "{{ secrets_in_file[entry.vault_key] }}"
    keyvault_uri: "https://{{ azure_vault_name }}.vault.azure.net/"
    state: present
  loop: "{{ vault_definitions }}"
  loop_control:
    loop_var: entry
    pause: 1
  delegate_to: localhost
