---
- name: Map vault_key → akv_secret_key and build new secret file content
  hosts: 192.168.124.100
  gather_facts: false
  become: false

  vars:
    base_secret_path: "/opt/NEXT/DevOps/ansible/files/secret"
    servicekeys_file: "../vars/servicekeys.yaml"

  tasks:

    - name: Load servicekeys definition
      ansible.builtin.include_vars:
        file: "{{ servicekeys_file }}"
        name: defs

    - name: Get unique vault file paths by environment
      ansible.builtin.set_fact:
        vault_paths: "{{ defs.servicekeys | selectattr('environment', 'equalto', ambiente) | selectattr('secret_type', 'equalto', s_type) | map(attribute='vault_path') | unique | list }}"

    - name: Check which vault paths exist on remote host
      ansible.builtin.stat:
        path: "{{ base_secret_path }}/{{ item }}"
      register: vault_path_stats
      loop: "{{ vault_paths }}"
      loop_control:
        label: "{{ item }}"

    - name: Filter only existing vault paths
      ansible.builtin.set_fact:
        existing_vault_paths: >-
          {{
            vault_path_stats.results |
            selectattr('stat.exists', 'equalto', true) |
            map(attribute='item') |
            list
          }}

    - name: Show missing vault paths
      ansible.builtin.debug:
        msg: "Missing vault files: {{ vault_paths | difference(existing_vault_paths) }}"
      when: (vault_paths | difference(existing_vault_paths) | length) > 0

    - name: Process each vault file
      ansible.builtin.include_tasks: ../tasks/process_vault_file.yml
      loop: "{{ existing_vault_paths }}"
      loop_control:
        loop_var: vault_path
      when: existing_vault_paths | length > 0

    - name: Delete all keys in Azure Key Vault
      ansible.builtin.include_tasks: ../tasks/delete_all_keys.yml
      tags: delete_all_secrets
      when: "'delete_all_secrets' in ansible_run_tags"
