---
- name: Map vault_key → akv_secret_key and build new secret file content
  hosts: 192.168.124.103
  gather_facts: false
  become: false

  vars:
    base_secret_path: "/opt/NEXT/Devops/ansible/files/secret"
    servicekeys_file: "../vars/servicekeys.yml"
    ambiente: "tu"

  tasks:

    - name: Load servicekeys definition
      ansible.builtin.include_vars:
        file: "{{ servicekeys_file }}"
        name: defs

    - name: Get unique vault file paths by environment
      ansible.builtin.set_fact:
        vault_paths: "{{ defs.servicekeys | selectattr('environment', 'equalto', ambiente) | map(attribute='vault_path') | unique | list }}"

    - name: Process each vault file
      ansible.builtin.include_tasks: ../tasks/process_vault_file.yml
      loop: "{{ vault_paths }}"
      loop_control:
        loop_var: vault_path

    - name: Delete all keys in Azure Key Vault
      ansible.builtin.include_tasks: ../tasks/delete_all_keys.yml
      tags: delete_all_secrets
